apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: vcluster
  namespace: vcluster
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: kind
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: kind
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: vcluster
  namespace: vcluster
spec:
  controlPlaneEndpoint:
    host: "kind.vcluster.svc"
    port: 443
  helmRelease:
    values: |-
      service:
        type: NodePort
  kubernetesVersion: 1.23.4
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: vcluster
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/tatskaari/fleet-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: vcluster
spec:
  interval: 1m0s
  path: ./workload/flux-system
  prune: true
  kubeConfig:
    secretRef:
      name: vcluster-kubeconfig
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vcluster
  namespace: vcluster
spec:
  interval: 1m0s
  path: ./vcluster
  prune: true
  kubeConfig:
    secretRef:
      name: vcluster-kubeconfig
  sourceRef:
    kind: GitRepository
    name: flux-system