apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: kind
  namespace: vcluster
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: kind
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: kind
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: kind
  namespace: vcluster
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    values: |-
      service:
        type: NodePort
  kubernetesVersion: 1.23.4
