---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fleet
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./fleet
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
